
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pharma-web:/app 
      - web_dados:/app/data
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dados_mysql:/var/lib/mysql

volumes:
  dados_mysql:
  web_dados:
