version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pharma-web:/app  # Mapeia os arquivos locais do projeto
      - web_dados:/app/data  # Cria um volume persistente para os dados gerados pelo app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_dados:/var/lib/mysql  # Volume persistente para o banco de dados

volumes:
  web_dados:
  db_dados:
