version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user_password
      MYSQL_DATABASE: pharmacy
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  
  web:
    build:
      context: ./backend  # Altere para o caminho correto do seu Dockerfile
    image: radallin/django-mysql:v1.1  # Substitua pelo seu usuário e repositório
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://mysql_user:mysql_user_password@db/pharmacy

volumes:
  db_data:
