# Generated by Django 5.1.3 on 2024-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_clientes_fornecedores_funcionarios_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='senha',
            field=models.CharField(default='senha', max_length=50),
            preserve_default=False,
        ),
    ]
